GET http://localhost:3003/users
###

POST http://localhost:3003/users/signup
Content-Type: application/json

  {
    "name": "Julio",
    "email": "julio@email.com",
    "password": "12543212",
    "role": "user"
  }
###

POST http://localhost:3003/users/login
Content-Type: application/json

  {
    "name": "Julio",
    "email": "julio@email.com",
    "password": "12543212",
    "role": "user"
  }
###

PUT http://localhost:3003/users/u006
Content-Type: application/json

  {
    "id": "u006",
    "name": "João Lucas",
    "email": "joaolucas@email.com",
    "password": "88239111",
    "role": "admin"
  }
###

DELETE  http://localhost:3003/users/u006
###

///////////////////////////////////////////////////////////////////////////////////////////

GET http://localhost:3003/posts
###

POST http://localhost:3003/posts
Content-Type: application/json

  {
    "id": "post5",
    "creator_id": "user5",
    "content": "Quinto post",
    "likes": 5,
    "dislikes": 1
  }
###

PUT http://localhost:3003/posts/post4
Content-Type: application/json

  {
    "id": "post4",
    "creator_id": "user4",
    "content": "Quarto Post",
    "likes": 5,
    "dislikes": 1
  }
###

DELETE  http://localhost:3003/posts/post5
###