GET http://localhost:3003/users
###

POST http://localhost:3003/users
Content-Type: application/json

  {
    "id": "u005",
    "name": "André",
    "email": "andre@email.com",
    "password": "33323212",
    "role": "user"
  }
###

PUT http://localhost:3003/users/u008
Content-Type: application/json

  {
    "id": "u008",
    "name": "Joãozinho",
    "email": "joazinho@email.com",
    "password": "88239111",
    "role": "admin"
  }
###

DELETE  http://localhost:3003/users/u008
###

///////////////////////////////////////////////////////////////////////////////////////////

GET http://localhost:3003/posts
###

POST http://localhost:3003/posts
Content-Type: application/json

  {
    "id": "post7",
    "creator_id": "user7",
    "content": "Sétimo post",
    "likes": 8,
    "dislikes": 1
  }
###

PUT http://localhost:3003/posts/post1
Content-Type: application/json

  {
    "id": "post1",
    "creator_id": "user1",
    "content": "Primeiro Post",
    "likes": 10,
    "dislikes": 12
  }
###

DELETE  http://localhost:3003/posts/post8
###