GET http://localhost:3003/users
###

POST http://localhost:3003/users
Content-Type: application/json

  {
    "id": "u006",
    "name": "Lucas",
    "email": "lucas@email.com",
    "password": "34323212",
    "role": "user"
  }
###

PUT http://localhost:3003/users/u006
Content-Type: application/json

  {
    "id": "u006",
    "name": "João Lucas",
    "email": "joaolucas@email.com",
    "password": "88239111",
    "role": "admin"
  }
###

DELETE  http://localhost:3003/users/u006
###

///////////////////////////////////////////////////////////////////////////////////////////

GET http://localhost:3003/posts
###

POST http://localhost:3003/posts
Content-Type: application/json

  {
    "id": "post5",
    "creator_id": "user5",
    "content": "Quinto post",
    "likes": 5,
    "dislikes": 1
  }
###

PUT http://localhost:3003/posts/post9
Content-Type: application/json

  {
    "id": "post8",
    "creator_id": "user1",
    "content": "Oitavo Post",
    "likes": 10,
    "dislikes": 12
  }
###

DELETE  http://localhost:3003/posts/post5
###